backend:
  name: github
  repo: oshuwa/theabc  # Replace with your actual GitHub username/repo
  branch: main # Branch to update

media_folder: "images/uploads" # Where media will be stored
public_folder: "/images/uploads" # Where media is accessed from the public site

collections:
  - name: "poems" # Used in routes, e.g., /admin/collections/poems
    label: "Poem" # Used in the UI
    folder: "_poems" # The path to the folder where poems are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}" # Filename template, e.g., 2025-04-25
    fields: # The fields for each document
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Content", name: "content", widget: "text"}
    # other collection settings...
    fields:
      - label: 'Publish Date'
        name: 'date'
        widget: 'datetime'
        date_format: 'YYYY-MM-DD' # Date format
        time_format: 'hh:mm A'    # 12-hour time format with AM/PM
        format: 'YYYY-MM-DD hh:mm A' # Combined format saved to file
# CMS configuration
locale: 'en'
# Set to UTC timezone
timezone: 'UTC'
